---
- name: "Enable Zabbix yum repository"
  ansible.builtin.yum_repository:
    name: zabbix
    description: "Zabbix repository"
    file: "zabbix"
    baseurl: "{{ repo_url }}"
    gpgcheck: true
    gpgkey: "{{ zabbix_rpm_gpg_key }}"
- name: "Install required packages"
  ansible.builtin.package:
    name: "{{ pkglist }}"
    state: present
