---
- name: "Add zabbix repo key"
  apt_key:
    url: "{{ zabbix_repo_key }}"
    state: present
  become: True
- name: "Enable Zabbix repos"
  apt_repository:
    repo: "deb [arch={{ repo_arch }}] {{ repo_url }} {{ ansible_lsb.codename }} main"
    state: present
    filename: "zabbix"
  become: True
- name: "Install required packages"
  apt:
    name: "{{ pkglist }}"
    update_cache: True
    autoremove: True
    state: latest
  become: True
...