---
- name: "Install dependencies packages"
  ansible.builtin.apt:
    name: "{{ deplist }}"
    update_cache: true
    autoremove: true
    state: present
  when: deplist is defined
- name: "Reload Facts"
  ansible.builtin.setup:
    gather_subset: "min,local"
- name: "Add zabbix repo key"
  ansible.builtin.apt_key:
    url: "{{ zabbix_repo_key }}"
    state: present
- name: "Enable Zabbix repos"
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ repo_arch }}] {{ repo_url }} {{ ansible_lsb.codename }} main"
    state: present
    filename: "zabbix"
- name: "Install required packages"
  ansible.builtin.apt:
    name: "{{ pkglist }}"
    update_cache: true
    autoremove: true
    state: present
