---
- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}"
- name: "Debug"
  ansible.builtin.debug:
    msg: "{{ ansible_lsb.id }}-{{ ansible_lsb.major_release }}"
- name: "Include os specific variables"
  ansible.builtin.include_vars: "vars-{{ ansible_lsb.id }}-{{ ansible_lsb.major_release }}.yml"
  when: ansible_lsb.id is defined
- name: "Include os specific variables"
  ansible.builtin.include_vars: "vars-{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"
  when: ansible_lsb.id is not defined
- name: "Call install-zabbix-agent task for RedHat like systems"
  ansible.builtin.include_tasks: install-zabbix-agent-RedHat.yml
  when: ansible_distribution_file_variety == "RedHat"
- name: "Call install-zabbix-agent task for Debian like systems"
  ansible.builtin.include_tasks: install-zabbix-agent-Debian.yml
  when: ansible_distribution_file_variety == "Debian"
- name: "Call configure-zabbix-agent task"
  ansible.builtin.include_tasks: configure-zabbix-agent.yml
